### ISSUE TITLE
Feature to flatten menu

### ISSUE THREAD

**Issue by jordwalke** [mbadran/headlights#20]
It would be great to be able to flatten the menu structure to look more like Textmate's bundle menu. Each plugin could have its own sub-menu, and within that submenu all the options/keymappings are in a single location. The groupings "a-i", "j-.." aren't really needed in this case.

**Comment by mbadran** [comment]
Hi Jordon,

Actually, that used to be an option. I took it out because I realised that for the average use case -- ie. someone who has installed enough plugins that they need visibility and centralisation -- menu navigation would be quite difficult, especially when you factor in all the default runtime plugins.

I'll leave this issue open for a while, and if it receives other votes, I'll bring it back.

**Comment by mbadran** [comment]
I've thought about this some more and decided to implement flat menus and make it the default behaviour. It actually works out better for performance, and the usability is fine if you don't have too many plugins.

I'll push this change after I do some more testing.

**Comment by mbadran** [comment]
Hi Jordan,

I've now pushed this feature as the default behaviour. Update the plugin and you should get the changes. If you have any problems, please let me know.

Cheers.

**Comment by jordwalke** [comment]
Just tried it out. Looks great! It would be cool if there was some convention/standard for plugin authors to be able to control how their plugin features show up in headlights.

**Comment by mbadran** [comment]
Thanks Jordan.

That's an interesting idea. Did you mean individually including or excluding category submenus (commands, mappings, etc), or did you have something else in mind?

**Comment by mbadran** [comment]
I've officially released the update so it's time to close this issue.
